# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0003_worker_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.WorkerMethod')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=utils.models.create_uuid, max_length=32)),
                ('name', models.CharField(max_length=30)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_message', models.CharField(max_length=100)),
                ('is_paused', models.BooleanField(default=False)),
                ('has_started', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('was_stopped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(help_text='01:05:03 = 1 hour, 5 minutes and 3 seconds')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureSchedule',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brew.Schedule')),
            ],
            bases=('brew.schedule',),
        ),
        migrations.AddField(
            model_name='schedule',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brew.Session'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.Worker'),
        ),
        migrations.AddField(
            model_name='eventaction',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Schedule'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Schedule'),
        ),
        migrations.AddField(
            model_name='temperaturetime',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.TemperatureSchedule'),
        ),
    ]
