# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brewer', models.CharField(max_length=128)),
                ('style', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('profile', models.TextField()),
                ('ingredients', models.TextField()),
                ('web_link', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('worker_type', models.CharField(max_length=128)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Recipe')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('unit', models.CharField(max_length=128)),
                ('target', models.FloatField(max_length=128)),
                ('hold_time', models.IntegerField(default=1)),
                ('time_unit_seconds', models.IntegerField(choices=[(1, 'Seconds'), (60, 'Minutes'), (3600, 'Hours'), (86400, 'Days')], default=60)),
                ('recipesection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.RecipeSection')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
