sudo: required
services:
  - docker
language: bash

branches:
  only:
    - master

jobs:
  include:
    - stage: Build x64 image
      script:
      - docker build -t distribrewed/master:x64 -f Dockerfile .
      - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      - docker push distribrewed/master:x64
#    - stage: Test docker pull
#      script:
#      - docker run -t distribrewed/master:x64 python --version
