# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0002_workermethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_message', models.CharField(max_length=100)),
                ('is_paused', models.BooleanField(default=False)),
                ('has_started', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.Worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperatureTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.TemperatureSchedule')),
            ],
        ),
    ]
