# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureschedule',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.Worker'),
        ),
        migrations.AlterField(
            model_name='temperaturetime',
            name='duration',
            field=models.DurationField(help_text='01:05:03 = 1 hour, 5 minutes and 3 seconds'),
        ),
    ]
