# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20170929_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatureschedule',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperatureschedule',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
