# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20170929_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatureschedule',
            name='uuid',
            field=models.CharField(default=utils.models.create_uuid, max_length=32),
        ),
    ]
