# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_temperatureschedule_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatureschedule',
            name='was_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
