postgres:
  image: distribrewed/postgres:x64
  environment:
    POSTGRES_DB: ${DB_NAME}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASS}
  ports:
    - "5432:5432"
  restart: always
rabbitmq:
  image: rabbitmq:3-management-alpine
  environment:
    RABBITMQ_DEFAULT_USER: ${AMQP_USER}
    RABBITMQ_DEFAULT_PASS: ${AMQP_PASS}
    RABBITMQ_DEFAULT_VHOST: ${AMQP_VHOST}
  ports:
    - "5672:5672"
    - "8100:15672"
  restart: always
prometheus:
  image: distribrewed/prometheus:x64
  links:
    - consul
  ports:
    - "9090:9090"
  restart: always
consul:
  image: consul
  environment:
    CONSUL_LOCAL_CONFIG: '{"datacenter": "distribrewed"}'
  ports:
    - "8500:8500"
  restart: always
grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  restart: always