postgres:
  image: distribrewed/postgres:x64
  environment:
    POSTGRES_DB: ${DB_NAME}
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASS}
  net: host
rabbitmq:
  image: rabbitmq:3-management-alpine
  environment:
    RABBITMQ_DEFAULT_USER: ${AMQP_USER}
    RABBITMQ_DEFAULT_PASS: ${AMQP_PASS}
    RABBITMQ_DEFAULT_VHOST: ${AMQP_VHOST}
  net: host
prometheus:
  image: distribrewed/prometheus:x64
  net: host
consul:
  image: consul
  environment:
    CONSUL_LOCAL_CONFIG: '{"datacenter": "distribrewed"}'
  net: host
grafana:
  image: grafana/grafana
  net: host