# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('prometheus_scrape_port', models.IntegerField(null=True)),
                ('last_registered', models.DateTimeField()),
                ('last_answered_ping', models.DateTimeField(null=True)),
                ('is_answering_ping', models.BooleanField(default=False)),
            ],
        ),
    ]
