# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
