# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 19:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Worker')),
            ],
        ),
    ]
