# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 03:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='events',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
        ),
    ]
