# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 11:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='grafana_rows',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
